In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
def dayOfYear(month, day, year):
    daysInMonth = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    dayOfYear = sum(daysInMonth[:int(month)-1]) + int(day)
    if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0) and dayOfYear > 59:
        dayOfYear -= 1
    return dayOfYear

In [3]:
def preprocessing(df):
    
    df['ArrivalDayOfYear'] = df.apply(lambda row: dayOfYear(row['ArrivalMonth'], row['ArrivalDate'], row['ArrivalYear']), axis=1)
    
    df['TotalNights'] = df['NumWeekendNights'] + df['NumWeekNights']

    df['TotalGuests'] = df['NumAdults'] + df['NumChildren']
    
    df['TotalPrice'] = df['AvgRoomPrice'] * df['TotalNights']

In [4]:
df = pd.read_csv('train.csv')
preprocessing(df)

In [5]:
df

,BookingID,LeadTime,ArrivalYear,ArrivalMonth,ArrivalDate,NumWeekendNights,NumWeekNights,MealPlan,Parking,RoomType,...,RepeatedGuest,NumPrevCancellations,NumPreviousNonCancelled,AvgRoomPrice,SpecialRequests,BookingStatus,ArrivalDayOfYear,TotalNights,TotalGuests,TotalPrice
0,1,10,2018,3,31,0,1,Meal Plan 1,0,Room_Type 1,...,0,0,0,95.00,0,Canceled,90,1,1,95.00
1,2,116,2018,2,28,2,1,Meal Plan 1,0,Room_Type 1,...,0,0,0,61.00,0,Canceled,59,3,1,183.00
2,3,11,2018,7,25,1,2,Meal Plan 1,0,Room_Type 1,...,0,0,0,129.75,1,Not_Canceled,206,3,3,389.25
3,4,3,2017,9,12,0,1,Meal Plan 1,0,Room_Type 1,...,0,0,0,152.00,3,Not_Canceled,255,1,2,152.00
4,5,28,2018,3,7,1,3,Meal Plan 1,0,Room_Type 1,...,0,0,0,87.00,0,Not_Canceled,66,4,2,348.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29015,29016,2,2018,11,21,1,2,Meal Plan 1,0,Room_Type 1,...,0,0,0,100.67,1,Not_Canceled,325,3,1,302.01
29016,29017,18,2018,4,12,0,2,Not Selected,0,Room_Type 1,...,0,0,0,119.00,1,Not_Canceled,102,2,2,238.00
29017,29018,8,2017,9,29,0,3,Meal Plan 1,0,Room_Type 1,...,0,0,0,65.00,0,Not_Canceled,272,3,1,195.00
29018,29019,20,2018,9,18,2,2,Meal Plan 1,0,Room_Type 1,...,0,0,0,90.00,0,Canceled,261,4,1,360.00
29019,29020,274,2018,7,31,2,1,Meal Plan 1,0,Room_Type 2,...,0,0,0,96.50,1,Not_Canceled,212,3,2,289.50